AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: motiv-serverless

Globals:
  Function:
    Timeout: 10
    LoggingConfig:
      LogFormat: JSON

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/
      Handler: helloHandler.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /yo
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        EntryPoints:
          - helloHandler.ts

  AddUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/userHandlers/
      Handler: addUserHandler.addUserHandler
      Runtime: nodejs18.x
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDbUriParameter
          MONGODB_DB_NAME: motiv
          # MONGODB_URI: mongodb+srv://anna:mongo-anna@core.9cr0y.mongodb.net/?retryWrites=true&w=majority&appName=Core
          # MONGODB_DB_NAME: motiv
      Events:
        AddUser:
          Type: Api
          Properties:
            Path: /user
            Method: post

  GetUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/userHandlers/
      Handler: getAllUsersHandler.getAllUsersHandler
      Runtime: nodejs18.x
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDbUriParameter
          MONGODB_DB_NAME: motiv
      Events:
        GetUsers:
          Type: Api
          Properties:
            Path: /users
            Method: get

Parameters:
  MongoDbUriParameter:
    Type: String
    Description: MongoDB connection URI
